### ISSUE TITLE
Doesn't start {paper 1.15.1}

### ISSUE THREAD

**Issue by LucianDevran** [dscalzi/SkyChanger#4]
[13:22:22] [Server thread/ERROR]: Could not load 'plugins/SkyChanger-Bukkit-3.0.1.jar' in folder 'plugins'
org.bukkit.plugin.InvalidDescriptionException: Invalid plugin.yml
	at org.bukkit.plugin.java.JavaPluginLoader.getPluginDescription(JavaPluginLoader.java:167) ~[craftbukkit.jar:git-Paper-62]
	at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:142) ~[craftbukkit.jar:git-Paper-62]
	at org.bukkit.craftbukkit.v1_15_R1.CraftServer.loadPlugins(CraftServer.java:356) ~[craftbukkit.jar:git-Paper-62]
	at net.minecraft.server.v1_15_R1.DedicatedServer.init(DedicatedServer.java:226) ~[craftbukkit.jar:git-Paper-62]
	at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:884) ~[craftbukkit.jar:git-Paper-62]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_171]
Caused by: java.util.zip.ZipException: error in opening zip file
	at java.util.zip.ZipFile.open(Native Method) ~[?:1.8.0_171]
	at java.util.zip.ZipFile.<init>(ZipFile.java:225) ~[?:1.8.0_171]
	at java.util.zip.ZipFile.<init>(ZipFile.java:155) ~[?:1.8.0_171]
	at java.util.jar.JarFile.<init>(JarFile.java:166) ~[?:1.8.0_171]
	at java.util.jar.JarFile.<init>(JarFile.java:130) ~[?:1.8.0_171]
	at org.bukkit.plugin.java.JavaPluginLoader.getPluginDescription(JavaPluginLoader.java:155) ~[craftbukkit.jar:git-Paper-62]
	... 5 more

**Comment by LucianDevran** [comment]
You need to change the API version to 1.15 in plugin.yml

**Comment by LucianDevran** [comment]
But how do make it so it keeps the sky? Kinda annoying if you have to run the command every time someone joins the world

**Comment by dscalzi** [comment]
I really hate how spigot is deciding my plugin isn't compatible with certain versions, when it undoubtably is. Such a braindead system.

**Comment by dscalzi** [comment]
I take that back, the latest version of the plugin is working fine on spigot 1.15.2. I'm not bumping the API version until they force me to otherwise I lose support for older versions.

**Comment by dscalzi** [comment]
I suggest filing an issue with Paper as they should not be breaking compatibility if the project they're based off of has not.
